In [280]:
#Import NumPy as np and installation

In [3]:
!pip install numpy

In [5]:
import numpy as np

In [7]:
#Create an array of 10 zeros

In [19]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
#Create an array of 10 ones.

In [15]:
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
#Create an array of 10 fives.

In [31]:
arr=np.zeros(10)+5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [33]:
arr=np.zeros(10,dtype=int)+5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [35]:
#Create an array of the integers from 10 to 50

In [41]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [43]:
#Create an array of all the even integers from 10 to 50.

In [45]:
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [47]:
#Create a 3x3 matrix with values ranging from 0 to 8.
# not possiable to create 3x3 matrix using values range(0,8)

In [82]:
mat=np.arange(0,9)

In [84]:
mat.shape

(9,)

In [86]:
mat.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
#Create a 3x3 identity matrix.

In [110]:
I=np.eye(3,dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [112]:
## OR

In [116]:
I=np.identity(3,dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
##Use NumPy to generate a random number between 0 and 1.
## we can create array using 1 and 1 instedof 0 and 1.

In [146]:
arr=np.random.rand(0,1)
arr

array([], shape=(0, 1), dtype=float64)

In [176]:
arr=np.random.rand(1,1)
arr

array([[0.42835663]])

In [178]:
##Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [180]:
arr=np.random.randn(25)
arr

array([-0.27780314, -0.56467189,  0.49745192, -0.79762278,  0.55933157,
        0.08379453,  0.39770834,  0.54501905, -0.59640448, -1.08672381,
       -0.02568261, -0.11532567, -0.4007001 ,  0.3642129 , -0.66694188,
       -0.33114487, -0.03780381,  0.19079019,  0.52480389,  1.08097988,
       -1.85288813, -0.93166452,  0.6488488 ,  0.25699758, -1.14259156])

In [ ]:
#Create the following matrix:

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

# ????????

In [236]:
#Create an array of 20 linearly spaced points between 0 and 1:

In [238]:
arr=np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [240]:
#Numpy Indexing and Selection
#Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [248]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# # WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [250]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [252]:
# OR
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [254]:
# find 20

In [256]:
arr[3,4]

20

In [258]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [264]:
arr[4,0:]
# OR
arr[4:,0:5]

array([[21, 22, 23, 24, 25]])

In [282]:
arr[3:,0:]
# OR 
arr[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#Get the sum of all the values in mat
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [322]:
np.sum(arr)
# OR
arr.sum()


325

In [333]:
#Get the standard deviation of the values in mat.
#7.2111025509279782

###????????????

In [284]:
#Get the sum of all the columns in mat.

In [326]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

In [290]:
# to get 15

In [298]:
arr[2,4]

15

In [318]:
arr[[3,3],[0,4]]

array([16, 20])